FROM postgres:15.3-alpine3.18
WORKDIR /var/lib/postgresql/data/
VOLUME ./postgres_volume
ENV POSTGRES_USER=postgres_user
ENV POSTGRES_PASSWORD=postgres_password
ENV POSTGRES_DB=postgres_dev
EXPOSE 5432

# python install
RUN apk add --update --no-cache python3
RUN ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

#Django
WORKDIR /usr/src/app
VOLUME ./app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG=1
ENV SECRET_KEY=django_secretkey
ENV ALLOWED_HOSTS="localhost 127.0.0.1"

# for postgres:
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

RUN apk add nginx
RUN rm /etc/nginx/http.d/default.conf
COPY nginx.conf /etc/nginx/http.d/

#RUN pip install --upgrade pip  -- commented out for escape unwanted pip modify in future
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
COPY entrypoint.sh /docker-entrypoint-initdb.d/
EXPOSE 8000
EXPOSE 80
#ENTRYPOINT /usr/src/app/entrypoint.sh
#ENTRYPOINT /usr/src/app/entrypoint.sh python manage.py migrate
#ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
#CMD python manage.py runserver 0.0.0.0:8000